

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
  
    keychain_name = "login"
    keychain_password = "tristate123"
    ensure_temp_keychain(keychain_name, keychain_password)
    
    match(
      type: 'appstore',
      app_identifier: "com.CICD",
      git_basic_authorization: Base64.strict_encode64(ENV["tristateAkshay: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"]),
      readonly: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password
    )
    
  increment_build_number(xcodeproj: "GitHubCICD.xcodeproj")
    sync_code_signing(
      type: "appstore",
      app_identifier: 'com.CICD',
      readonly: true
    )

    build_app(scheme: "GitHubCICD")
    app_store_connect_api_key(
      is_key_content_base64: true,
      in_house: false, # if it is enterprise or not
    )
    
  enable_automatic_code_signing(path: "GitHubCICD.xcodeproj")
  
  upload_to_testflight
    
  end
end
