# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
  
    delete_keychain(name: "GitHubCICD") if File.exist? File.expand_path("~/Library/Keychains/#{keychain_name}-db")

    create_keychain(name: keychain_name, default_keychain: true, unlock: true, timeout: 3600, lock_when_sleeps: true)

    match(keychain_name: keychain_name,readonly: true)
      
      
    output_directory = '.archives'
    output_name = 'GitHubCICD-AppStore.ipa'
    output_file_path = "#{output_directory}/#{output_name}"

    gym(project: project,silent: true,clean: true, export_method: "app-store", export_options: {
      provisioningProfiles: {
        app_target_bundle_identifier => app_target_profile_name
      }
    },
    output_directory: output_directory,
    output_name: output_name)
    
    increment_build_number(xcodeproj: "GitHubCICD.xcodeproj")
    build_app(scheme: "GitHubCICD")
    upload_to_testflight
  end
end
