name: CI

on:
  push:
    branches: [ main ]
jobs:
  deploy:
    name: Deploy
    runs-on: macos-latest
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          ref: ${{ github.ref }}
    - name: Install GPG
      run: brew install gnupg
      
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
      
    
      
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: false
    - name: Decrypt large secret
      run: ./provisioning/import_provisioning.sh
      env:
        PROVISIONING_PASSWORD: ${{ secrets.PROVISIONING_PASSWORD }}
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
      
    - name: Setup fastlane
      run: sudo gem install fastlane
      
    - name: Increment Build Number
      run: fastlane beta
      
   
