name: CI

on:
    push:
    branches:
        - main

jobs:
    deploy:
    name: Deploy
    runs-on: macos-latest
    
    steps:
    - name: Checkout
        uses: actions/checkout@v2
    
    - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
        xcode-version: latest-stable
    
    - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
        ruby-version: 2.7.2
        bundler-cache: true
    
    - name: Install Pods
        run: pod install
    
    - name: Build & Distribute to Testflight
        run: bundle exec fastlane build
        # Export the needed environment variables
        env:
            APP_STORE_CONNECT_API_KEY_ISSUER_ID: $
            APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64: $
            APP_STORE_CONNECT_API_KEY_KEY: $
            APP_STORE_CONNECT_API_KEY_KEY_ID: $
            FASTLANE_TEAM_ID: $
            MATCH_PASSWORD: $
            KEYCHAIN_PASSWORD: $
            MATCH_KEYCHAIN_PASSWORD: $
            APP_STORE_CERT_NAME: $



