# This is a basic workflow to help you get started with Actions

name: main

#name: Swift

on:
    push:
        branches: [main]

jobs:
    build:
    
    runs-on: macos-latest
    
    steps:
        uses: actions/checkout
        run: fastlane beta

        env:
            MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

    
