name: CI

on:
  push:
    branches: [ main ]
jobs:
  deploy:
    name: Deploy
    runs-on: macos-latest
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
      
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
            
    - name: Build & Distribute to Testflight
      run:
        bundle exec fastlane beta
     



