name: CI

on:
    push:
    branches:
        - main

jobs:
    build:
    name: build
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Select Xcode Version
      run : sudo xcode-select -s /Applications/Xcode.app

#    - name: Setup ruby
#        uses: ruby/setup-ruby@v1
#        with:
#        ruby-version: 3.0.0
#        bundler-cache: true
    
    - name: Install Pods
        run: pod install
    
#    - name: Build & Distribute to Testflight
#        run: bundle exec fastlane build
#        # Export the needed environment variables
#        env:
#            APP_STORE_CONNECT_API_KEY_ISSUER_ID: $
#            APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64: $
#            APP_STORE_CONNECT_API_KEY_KEY: $
#            APP_STORE_CONNECT_API_KEY_KEY_ID: $
#            FASTLANE_TEAM_ID: $
#            MATCH_PASSWORD: $
#            KEYCHAIN_PASSWORD: $
#            MATCH_KEYCHAIN_PASSWORD: $
#            APP_STORE_CERT_NAME: $



